### ISSUE TITLE
init with home path alias doesn't seem to work

### ISSUE THREAD

**Issue by travismcchesney** [cloud-elements/hykes-blueprinter#18]
#### Version
`master` branch

#### Steps to Reproduce
```bash
$ git clone git@github.com:cloud-elements/hykes-blueprinter.git
$ cd hykes-blueprinter
$ make dependencies
$ make install
$ build/bin/hykes-blueprinter init
Enter path: ~/path/to/blueprints
```

#### Expected Results
The path should be placed in the `etc/hykes-blueprinter` file.

#### Actual Results
The path is not placed in the `etc/hykes-blueprinter` file.

**Comment by rockymadden** [comment]
Are the steps to reproduce the literal commands entered? If so, can you confirm that `build/etc/hykes-blueprinter` is not present and/or does not have `~/path/to/blueprints` on the first line?

**Comment by rockymadden** [comment]
As an aside, I am removing all dependency targets from `make`. It was attempting to be a poor man's system package manager. This repo is the wrong spot to house this. In the future (i.e. later tonight), there will be two ways to install:

__If you are not a core developer:__
* Use your platform's package manager:
  * OS X: homebrew (will be ready with v0.0.0 tonight)
  * Debian: PPA (coming)

__If you are a core developer:__
* Hand compile the project and also hand compile all dependencies (like is normally required with system-level projects)

**Comment by rockymadden** [comment]
__v0.0.0 has been officially released:__
* It now has a functioning homebrew install:
  * https://github.com/cloud-elements/hykes-blueprinter#via-homebrew
  * https://github.com/cloud-elements/homebrew-hykes/blob/master/Formula/hykes-blueprinter.rb
* It should also work via compiling from source, but you are responsible for compiling all dependencies (including transitive). It fully passes all unit and integration tests on CircleCI (Ubuntu) and locally, but there could be something I am doing locally that I did not fully document or handle for. 

If you continue to encounter issues, please reopen this issue :smiley:
